### ISSUE TITLE
When I changed tab,it can't display particles

### ISSUE THREAD

**Issue by ThomasSoloist** [JoelBesada/activate-power-mode#89]
When I changed tab,it can't display particles

Windows 8.1

**Comment by itkang** [comment]
I think maybe you should upgrade it! It fixed in new version!

**Comment by ThomasSoloist** [comment]
@itkang Thank you, but my Atom shows this:" All of your installed packages are up to date! " , and my Activate Power Mode Package's version is 0.4.1, but it still can't display particles.

**Comment by Seraphli** [comment]
Yeah, I have the same problem

**Comment by eijil** [comment]
@ThomasSoloist  verserion is 0.4.1 is fiexd

**Comment by mimions** [comment]
Using version 0.4.1 on Mac. Still having this problem.

**Comment by xr08255920** [comment]
i have the same problem,i using 0.4.1 version on win10

**Comment by jspurim** [comment]
Same problem on 0.4.1, Ubuntu 15.10

**Comment by jamesrvandegrift** [comment]
Same problem `el capitan 10.11.4`

**Comment by lexcast** [comment]
Closing issues on old versions of this package.

Open again if the problem persists with the latest release.
